# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '>=22.0.0'
    checkLatest: true
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: './Scripts'
    customCommand: 'install'
- task: AzureStaticWebApp@0
  inputs:
    app_location: './Scripts'
    app_build_command: 'npm run build'
    output_location: './Scripts/dist/frontend3'
    skip_api_build: true
    azure_static_web_apps_api_token: '7512473fe40c61445aac4cebda7e4c7f7de0d309cc8a0e0fde925c1c13e0086a5-57c7f44a-61aa-401c-9640-a7be4554571801e162889'