# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: NodeTool@0
  name: 'Install_Nodejs'
  inputs:
    versionSource: 'spec'
    versionSpec: '>=22.0.0'
    checkLatest: true
- task: Npm@1
  name: 'Install_Frontend_Dependencies'
  inputs:
    command: 'custom'
    workingDir: './Scripts'
    customCommand: 'install'    
- task: Npm@1
  name: 'Build_Frontend_WebSite'
  inputs:
    command: 'custom'
    workingDir: './Scripts'
    customCommand: 'run build'
- task: AzureStaticWebApp@0
  name: 'Deploy_Frontend_WebSite'
  env:
    deploy_token: $(Deploy Token)
  inputs:
    app_location: './Scripts/dist/frontend3'
    skip_app_build: true
    skip_api_build: true
    is_static_export: true
    azure_static_web_apps_api_token: '$(env.deploy_token)'