# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
on:
  push:
    branches:
      - master
  workflow_dispatch:
name: Build and deploy ASP app to Azure Web App - alianbot0
jobs:
  build:
    runs-on: windows-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Restore NuGet packages
        run: nuget restore
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          # Set always-auth in npmrc.
          always-auth: false
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 16          
          # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
          architecture: x64
          # Set this option if you want the action to check for the latest available version that satisfies the version spec.
          check-latest: true
      - name: Build Frontend Files
        run: |
          cd Scripts
          npm i -g @angular/cli  
          npm i
          npm run publish
      - name: Publish to folder
        run: msbuild Alianbot.sln /verbosity:d /t:Clean,Build /p:_PackageTempDir="\published\"
      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
          # Specify the Az PowerShell script here.
          inlineScript:                     
            $WebApp = Get-AzWebApp -Name alianbot0 -ResourceGroupName Alianbot
            [xml]$publishingProfile = Get-AzWebAppPublishingProfile -WebApp $WebApp
            $username = $publishingProfile.publishData.publishProfile[0].userName
            $password = $publishingProfile.publishData.publishProfile[0].userPWD
            $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $username,$password)))
            
            $param = @{  
                        Uri = "https://alianbot0.scm.azurewebsites.net/api/vfs/site/wwwroot/*.*"  
                        Headers = @{Authorization=("Basic {0}" -f $base64AuthInfo)}  
                        Method = "DELETE
            }  
            Invoke-RestMethod @param  
          # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
          azPSVersion: latest
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'alianbot0'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_27529369AD0E478D8D1552287A681E4F }}
          package: .
