# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - alianbot0

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        uses: IT-Service/restore-nuget-packages@v1
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 17.3
      - name: install dependency
        run: |
          cd Scripts
          npm install -g @angular/cli
          npm install
          npm run build
      - name: Publish to folder
        run: msbuild Alianbot.sln /nologo /verbosity:m /t:backend3 /p:OutDir="obj/Release"
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'alianbot0'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5C79239316A6400CAE7E464BA6F0B092 }}
          package: .
